# Generated by Django 6.0.6 on 2026-06-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aktivitas', models.CharField(max_length=100)),
                ('durasi', models.PositiveIntegerField(help_text='Durasi dalam menit')),
                ('kalori_terbakar', models.PositiveIntegerField()),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
                ('kalori', models.PositiveIntegerField()),
                ('protein', models.FloatField()),
                ('karbohidrat', models.FloatField()),
                ('lemak', models.FloatField()),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berat_badan', models.FloatField()),
                ('tinggi_badan', models.FloatField()),
                ('detak_jantung', models.PositiveIntegerField()),
                ('tekanan_darah', models.CharField(max_length=30)),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('waktu', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('durasi_minggu', models.PositiveIntegerField()),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
